#This solution, non-production-ready template describes AWS Codepipeline based CICD Pipeline for terraform code deployment.
#© 2023 Amazon Web Services, Inc. or its affiliates. All Rights Reserved.
#This AWS Content is provided subject to the terms of the AWS Customer Agreement available at
#http://aws.amazon.com/agreement or other written agreement between Customer and either
#Amazon Web Services, Inc. or Amazon Web Services EMEA SARL or both.

version: 0.2

env:
  variables:
    CODE_SRC_DIR: "."
    SCRIPT_DIR: "./templates/scripts"
    TF_VERSION: "1.3.7"
    ENVIRONMENT: "dev"
    SKIPVALIDATIONFAILURE: "Y"
    ENABLE_TFVALIDATE: "Y"
    ENABLE_TFFORMAT: "Y"
    ENABLE_TFCHECKOV: "Y"
    ENABLE_TFSEC: "Y"
    TFSEC_VERSION: "v1.28.1"

phases:
  install:
    runtime-versions:
      python: 3.9
      golang: 1.14
    commands:
      - "curl -s -qL -o terraform.zip https://releases.hashicorp.com/terraform/${TF_VERSION}/terraform_${TF_VERSION}_linux_amd64.zip"
      - "unzip -o terraform.zip"
      - "mv terraform /bin"
      - "rm terraform.zip"
      - "yum update -y"
      - "yum install -y curl jq awscli"
      - "pip3 install checkov"
      - "yum install -y golang"
      - "wget -q -O tfsec https://github.com/aquasecurity/tfsec/releases/download/${TFSEC_VERSION}/tfsec-linux-amd64"
      - "chmod +x ./tfsec"
      - "mv ./tfsec /usr/local/bin/tfsec"
  pre_build:
    commands:
      - PUBLIC_KEY=$(aws ssm get-parameter --name "/path/ssm/key" --with-decryption --query 'Parameter.Value' --output text)
      - echo "$PUBLIC_KEY" > id_rsa.pub
      - # other pre-build commands:
  build:
    commands:
      - "cd ${CODEBUILD_SRC_DIR}/${CODE_SRC_DIR}"
      - "echo ${CODEBUILD_SRC_DIR}/${CODE_SRC_DIR}"
      - "ls -al ${CODEBUILD_SRC_DIR}/${CODE_SRC_DIR}"
      - "echo ## TERRAFORM INIT : Initialize the Terraform Workspace"
      # Set the AWS region
      - "export AWS_DEFAULT_REGION='us-east-1'"
      - |
        export TF_CLI_ARGS_init="-backend-config=bucket=piyushassignmenttestbucket \
        -backend-config=key=eks-us-east-1-prod-app-demo-terraform.tfstate \
        -backend-config=region=us-east-1 \
        -backend-config=dynamodb_table=terraform-state-lock-dynamodb"
      - "terraform init"
      - "echo ## VALIDATION : Starting  ..."
      - "mkdir -p ${CODEBUILD_SRC_DIR}/reports"
      - "/bin/bash ${CODEBUILD_SRC_DIR}/${SCRIPT_DIR}/tf_ssp_validation.sh ${SKIPVALIDATIONFAILURE} ${ENABLE_TFVALIDATE} ${ENABLE_TFFORMAT} ${ENABLE_TFCHECKOV} ${ENABLE_TFSEC}"
      - "cp checkov.xml ${CODEBUILD_SRC_DIR}/reports/checkov.xml"
      - "cp tfsec-junit.xml ${CODEBUILD_SRC_DIR}/reports/tfsec-junit.xml"
artifacts:
  files:
    - '**/*'
reports:
  checkov-reports:
    files:
      - "./reports/checkov.xml"
    file-format: "JUNITXML"
  tfsec-reports:
    files:
      - "./reports/tfsec-junit.xml"
    file-format: "JUNITXML"