apiVersion: v1
kind: Namespace
metadata:
  name: ns-2
---
# pod-2.yaml
apiVersion: v1
kind: Pod
metadata:
  name: pod-2
  labels:
    app: pod-2-label
  namespace: ns-2
spec:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: node-affinity-key
            operator: In
            values:
            - node-2
  containers:
  - name: nginx
    image: nginx

---
# service-2.yaml
apiVersion: v1
kind: Service
metadata:
  name: service-2
  namespace: ns-2
spec:
  selector:
    app: pod-2-label
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
