apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: database
type: Opaque
data:
  MYSQL_ROOT_PASSWORD: cGFzc3dkMQ==  # Base64-encoded value of "passwd1"
# ---
# apiVersion: v1
# kind: ConfigMap
# metadata:
#   name: app-config
#   namespace: your-namespace
# data:
#   imageArn: "943330243877.dkr.ecr.us-east-1.amazonaws.com/opstree/spring3hibernate:latest"
