apiVersion: v1
kind: PersistentVolume
metadata:
  name: task-pv-volume-20
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data"

