apiVersion: v1
kind: ConfigMap
metadata:
  name: aws-auth
  namespace: kube-system
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::943330243877:role/tf-validate-project-codepipeline-role
      username: system:node:{{EC2PrivateDNSName}}
  mapUsers: |
    - userarn: arn:aws:iam::943330243877:user/eks-trainee
      username: eks-trainee
    - userarn: arn:aws:iam::943330243877:user/developer
      username: eks-developer
    - userarn: arn:aws:iam::943330243877:user/piyushraj
      groups:
      - system:masters